// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID         *string `json:"id"`
	Name       *string `json:"name"`
	Email      *string `json:"email"`
	OrgID      *string `json:"orgId"`
	BranchID   *string `json:"branchId"`
	BranchName *string `json:"branchName"`
	RoleName   *string `json:"roleName"`
	Address    *string `json:"address"`
	Contact    *string `json:"contact"`
	LoginCode  *string `json:"loginCode"`
	FirstLogin *bool   `json:"firstLogin"`
}
