// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID         string  `json:"ID"`
	Email      *string `json:"Email"`
	OrgID      *string `json:"OrgId"`
	BranchID   *string `json:"BranchId"`
	BranchName *string `json:"BranchName"`
	RoleName   *string `json:"RoleName"`
	Address    *string `json:"Address"`
	Contact    *string `json:"Contact"`
	LoginCode  *string `json:"LoginCode"`
	FirstLogin *bool   `json:"FirstLogin"`
}
