port: 8090
db: 
    host: 'localhost'
    port: 5432
    name: 'table_manager'
    username: 'postgres'
    password: ''
secret: 123e4567#e89b&12d3*a4562426614174000
ui: ../frontend/build
uploads:
    base: ../frontend/build
    products: /images/products/