import { keyMirror } from '../modules/helpers';

/**
 * @namespace Constants
 * @desc App constants
 */

/**
 * @constant {Object} ActionTypes
 * @memberof Constants
 */
export const ActionTypes = keyMirror({
  EXCEPTION: undefined,
  USER_LOGIN: undefined,
  USER_LOGIN_SUCCESS: undefined,
  USER_LOGIN_FAILURE: undefined,
  USER_LOGOUT: undefined,
  USER_LOGOUT_SUCCESS: undefined,
  USER_LOGOUT_FAILURE: undefined,
  USER_REGISTER: undefined,
  USER_REGISTER_SUCCESS: undefined,
  USER_REGISTER_FAILURE: undefined,
  USER_EDIT: undefined,
  USER_EDIT_SUCCESS: undefined,
  USER_EDIT_FAILURE: undefined,
  SHOW_ALERT: undefined,
  HIDE_ALERT: undefined,
  BRANCH_ADD_INITIATE: undefined,
  BRANCH_ADD: undefined,
  BRANCH_ADD_SUCCESS: undefined,
  BRANCH_ADD_FAILURE: undefined,
  BRANCH_DELETE: undefined,
  BRANCH_DELETE_SUCCESS: undefined,
  BRANCH_DELETE_FAILURE: undefined,
  BRANCH_GET: undefined,
  BRANCH_GET_SUCCESS: undefined,
  BRANCH_GET_FAILURE: undefined,
  BRANCHES_GET: undefined,
  BRANCHES_GET_SUCCESS: undefined,
  BRANCHES_GET_FAILURE: undefined,
  BRANCH_GET_TOP_PRODUCTS: undefined,
  BRANCH_SET_IN_STATE: undefined,
  BRANCH_GET_TOP_PRODUCTS_SUCCESS: undefined,
  BRANCH_GET_TOP_PRODUCTS_FAILURE: undefined,
  TABLE_ADD_INITIATE: undefined,
  SET_SELECTED_TABLE: undefined,
  EDIT_TABLE: undefined,
  EDIT_TABLE_SUCCESS: undefined,
  EDIT_TABLE_FAILURE: undefined,
  TABLE_ADD: undefined,
  TABLE_ADD_SUCCESS: undefined,
  TABLE_ADD_FAILURE: undefined,
  TABLE_GET_BY_CODE: undefined,
  TABLE_GET_BY_CODE_SUCCESS: undefined,
  TABLE_GET_BY_CODE_FAILURE: undefined,
  TABLE_GET: undefined,
  TABLE_GET_SUCCESS: undefined,
  TABLE_GET_FAILURE: undefined,
  TABLE_DELETE: undefined,
  TABLE_DELETE_SUCCESS: undefined,
  TABLE_DELETE_FAILURE: undefined,
  TABLES_GET: undefined,
  TABLES_GET_SUCCESS: undefined,
  TABLES_GET_FAILURE: undefined,
  TABLES_GET_BRANCH: undefined,
  TABLES_GET_ORG_SUCCESS: undefined,
  TABLES_GET_ORG_FAILURE: undefined,
  KITCHEN_ADD_INITIATE: undefined,
  KITCHEN_SET_IN_STATE: undefined,
  KITCHEN_ADD: undefined,
  KITCHEN_ADD_SUCCESS: undefined,
  KITCHEN_ADD_FAILURE: undefined,
  KITCHEN_EDIT: undefined,
  KITCHEN_EDIT_SUCCESS: undefined,
  KITCHEN_EDIT_FAILURE: undefined,
  KITCHEN_DELETE: undefined,
  KITCHEN_DELETE_SUCCESS: undefined,
  KITCHEN_DELETE_FAILURE: undefined,
  KITCHEN_GET: undefined,
  KITCHEN_GET_SUCCESS: undefined,
  KITCHEN_GET_FAILURE: undefined,
  KITCHENS_GET: undefined,
  KITCHENS_GET_SUCCESS: undefined,
  KITCHENS_GET_FAILURE: undefined,
  KITCHENS_GET_BRANCH: undefined,
  KITCHENS_GET_ORG_SUCCESS: undefined,
  KITCHENS_GET_ORG_FAILURE: undefined,
  PRODUCT_ADD_INITIATE: undefined,
  PRODUCT_ADD: undefined,
  PRODUCT_ADD_SUCCESS: undefined,
  PRODUCT_ADD_FAILURE: undefined,
  PRODUCT_DELETE: undefined,
  PRODUCT_DELETE_SUCCESS: undefined,
  PRODUCT_DELETE_FAILURE: undefined,
  PRODUCT_GET: undefined,
  PRODUCT_GET_SUCCESS: undefined,
  PRODUCT_GET_FAILURE: undefined,
  PRODUCT_SET_IN_STATE: undefined,
  PRODUCTS_GET: undefined,
  PRODUCTS_GET_SUCCESS: undefined,
  PRODUCTS_GET_FAILURE: undefined,
  ORDER_ADD_INITIATE: undefined,
  ORDER_ADD_PRODUCT: undefined,
  ORDER_REMOVE_PRODUCT: undefined,
  ORDER_ADD: undefined,
  ORDER_ADD_SUCCESS: undefined,
  ORDER_ADD_FAILURE: undefined,
  ORDER_UPDATE: undefined,
  ORDER_UPDATE_SUCCESS: undefined,
  ORDER_UPDATE_FAILURE: undefined,
  ORDER_GET: undefined,
  ORDER_GET_SUCCESS: undefined,
  ORDER_GET_FAILURE: undefined,
  ORDERS_GET: undefined,
  ORDERS_GET_SUCCESS: undefined,
  ORDERS_GET_FAILURE: undefined,
  ORDER_GET_BY_TABLE_ID: undefined,
  ORDER_GET_BY_TABLE_ID_SUCCESS: undefined,
  ORDER_GET_BY_TABLE_ID_FAILURE: undefined,
  TAG_GET_SIMILAR: undefined,
  TAG_GET_SIMILAR_SUCCESS: undefined,
  TAG_GET_SIMILAR_FAILURE: undefined,
  CATEGORY_ADD_INITIATE: undefined,
  CATEGORY_ADD: undefined,
  CATEGORY_ADD_SUCCESS: undefined,
  CATEGORY_ADD_FAILURE: undefined,
  CATEGORY_GET: undefined,
  CATEGORY_GET_SUCCESS: undefined,
  CATEGORY_GET_FAILURE: undefined,
  CATEGORIES_GET: undefined,
  CATEGORIES_GET_SUCCESS: undefined,
  CATEGORIES_GET_FAILURE: undefined,
  CATEGORY_DELETE: undefined,
  CATEGORY_DELETE_SUCCESS: undefined,
  CATEGORY_DELETE_FAILURE: undefined,
  DASHBOARD_STATS_GET: undefined,
  DASHBOARD_STATS_GET_SUCCESS: undefined,
  DASHBOARD_STATS_GET_FAILURE: undefined,
  SETTINGS_EDIT: undefined,
  SETTINGS_EDIT_SUCCESS: undefined,
  SETTINGS_EDIT_FAILURE: undefined,
  GET_TIMEZONES: undefined,
  GET_TIMEZONES_SUCCESS: undefined,
  GET_TIMEZONES_FAILURE: undefined,
  GET_COUNTRIES: undefined,
  GET_COUNTRIES_SUCCESS: undefined,
  GET_COUNTRIES_FAILURE: undefined,
  GET_CURRENCIES: undefined,
  GET_CURRENCIES_SUCCESS: undefined,
  GET_CURRENCIES_FAILURE: undefined,
});

/**
 * @constant {Object} STATUS
 * @memberof Constants
 */
export const STATUS = {
  IDLE: 'idle',
  RUNNING: 'loading',
  READY: 'ready',
  SUCCESS: 'success',
  ERROR: 'exception',
};
